import { PortfolioKPI, AssetClassItem, PortfolioInsightData } from '../types/portfolio';

export const mockPortfolioKPIs: PortfolioKPI[] = [
  {
    id: 'total-portfolio',
    title: 'TOTAL PORTFOLIO',
    value: '₹100',
    unit: 'Cr',
    subtitle: 'Current portfolio value',
    change: '+3.2% vs last month',
    isPositive: true,
    statusText: 'Optimal',
    statusType: 'optimal',
    icon: 'Building2',
  },
  {
    id: 'total-assets',
    title: 'TOTAL ASSETS',
    value: '₹100',
    unit: 'Cr',
    subtitle: 'Across 4 asset classes',
    change: '100% Active Ledger',
    isPositive: true,
    statusText: 'Balanced Book',
    statusType: 'safe',
    icon: 'Layers',
  },
  {
    id: 'expected-return',
    title: 'EXPECTED RETURN',
    value: '7.4',
    unit: '%',
    subtitle: 'Projected annual return',
    change: '+45 bps frontier delta',
    isPositive: true,
    statusText: 'Yield Stable',
    statusType: 'safe',
    icon: 'TrendingUp',
  },
  {
    id: 'portfolio-risk',
    title: 'PORTFOLIO RISK',
    value: '72',
    unit: '/ 100',
    subtitle: 'Moderate risk exposure',
    change: '+4 pts in last 24h',
    isPositive: false,
    statusText: 'Watch / High',
    statusType: 'watch',
    icon: 'ShieldAlert',
  },
];

export const mockAssetClasses: AssetClassItem[] = [
  {
    id: 'loans',
    name: 'Loans',
    category: 'Commercial & Retail Credit',
    valueCr: 50.0,
    allocationPct: 50,
    targetPct: 42,
    differencePct: 8,
    riskLevel: 'Medium',
    riskScore: 78,
    expectedReturnPct: 8.2,
    status: 'OVERWEIGHT',
    color: '#1E3A8A', // Deep Navy / Slate
    fillColor: 'bg-blue-900',
    description: 'Direct lending books, infrastructure tranches, and retail advances.',
  },
  {
    id: 'bonds',
    name: 'Bonds',
    category: 'Sovereign & AAA Corporate Debt',
    valueCr: 30.0,
    allocationPct: 30,
    targetPct: 33,
    differencePct: -3,
    riskLevel: 'Low',
    riskScore: 28,
    expectedReturnPct: 6.1,
    status: 'UNDERWEIGHT',
    color: '#0D9488', // Teal
    fillColor: 'bg-teal-600',
    description: 'Central government sovereign securities, state debt, and AAA corporate bonds.',
  },
  {
    id: 'cash',
    name: 'Cash',
    category: 'Central Bank Reserves & Overnight',
    valueCr: 10.0,
    allocationPct: 10,
    targetPct: 15,
    differencePct: -5,
    riskLevel: 'Very Low',
    riskScore: 5,
    expectedReturnPct: 3.2,
    status: 'UNDERWEIGHT',
    color: '#16A34A', // Emerald
    fillColor: 'bg-emerald-600',
    description: 'Overnight clearing balances, statutory reserve ratio, and repo facilities.',
  },
  {
    id: 'equity',
    name: 'Equity',
    category: 'Listed Securities & Index Funds',
    valueCr: 10.0,
    allocationPct: 10,
    targetPct: 10,
    differencePct: 0,
    riskLevel: 'High',
    riskScore: 89,
    expectedReturnPct: 11.5,
    status: 'BALANCED',
    color: '#D97706', // Amber
    fillColor: 'bg-amber-600',
    description: 'Blue-chip equities, sector ETFs, and long-term capital dividend holdings.',
  },
];

export const mockPortfolioInsight: PortfolioInsightData = {
  title: 'CapitalGuard Insight',
  badge: 'Concentration Warning',
  headline: 'Portfolio concentration detected',
  description:
    'Loans currently represent 50% of the portfolio, which is 8% above the recommended target allocation. Increasing liquidity and bond exposure may improve portfolio resilience.',
  recommendationAction: 'Reallocate 8% (₹8 Cr) from Loans into Bonds (+3%) and Cash Liquidity (+5%).',
  targetRebalanceRoute: '/optimization',
};
